from models.vgg import *
from models.googlenet import *
from models.resnet import *
from models.efficientnet import *
from models.densenet import *
from models.convnext import *
from models.regnet import *
from models.s2mlpv1 import *
from models.volo import *
from models.xcit import *
from models.raft_mlp import *
from models.cait import *
from models.convmixer import *
from models.dla import *
from models.googlenet import *
from models.swin import *
from models.xception import *
from models.xcit import *
from models.simplevit import *
from models.mlpmixer import *

